/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./*.html",
    "./about/index.html",
    "./afvalkalender/index.html",
    "./bespaartips/index.html",
    "./container-omruilen/index.html",
    "./gft-aanvragen/index.html",
    "./grof-afval/index.html",
    "./hoe-werkt-diftar/index.html",
    "./hoogbouw-vs-laagbouw/index.html",
    "./kies-je-container/index.html",
    "./kwijtschelding/index.html",
    "./milieupas/index.html",
    "./nieuws/index.html",
    "./privacy/index.html",
    "./tarieven-2026/index.html",
    "./veelgestelde-vragen/index.html"
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#783200",
        "background": "#f7f9fb",
        "on-surface-variant": "#3d4a3d",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#ffb690",
        "surface-container-high": "#e6e8ea",
        "primary-fixed-dim": "#4ae176",
        "on-secondary-fixed": "#341100",
        "tertiary-fixed": "#d8e3fb",
        "surface-container": "#eceef0",
        "text-muted": "#94A3B8",
        "secondary-container": "#fd761a",
        "on-background": "#191c1e",
        "outline-variant": "#bccbb9",
        "on-primary-container": "#004b1e",
        "on-tertiary-container": "#354053",
        "on-tertiary": "#ffffff",
        "primary": "#006e2f",
        "surface-variant": "#e0e3e5",
        "outline": "#6d7b6c",
        "surface-container-low": "#f2f4f6",
        "inverse-surface": "#2d3133",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#002109",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "brand-red": "#EF4444",
        "surface-container-highest": "#e0e3e5",
        "surface-tint": "#006e2f",
        "inverse-on-surface": "#eff1f3",
        "brand-green-dark": "#16A34A",
        "bg-tertiary": "#F1F5F9",
        "bg-primary": "#FFFFFF",
        "error": "#ba1a1a",
        "on-secondary-container": "#5c2400",
        "on-tertiary-fixed-variant": "#3c475a",
        "text-primary": "#1E293B",
        "text-secondary": "#475569",
        "surface": "#f7f9fb",
        "surface-bright": "#f7f9fb",
        "primary-container": "#22c55e",
        "inverse-primary": "#4ae176",
        "secondary-fixed": "#ffdbca",
        "tertiary-container": "#a1acc3",
        "surface-dim": "#d8dadc",
        "tertiary": "#545f73"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "navbar-height": "64px",
        xl: "2rem",
        gutter: "1rem",
        sm: "0.5rem",
        "3xl": "4rem",
        "4xl": "6rem",
        "2xl": "3rem",
        xs: "0.25rem",
        lg: "1.5rem",
        md: "1rem",
        "container-max": "1152px"
      },
      fontFamily: {
        badge: ["Inter"],
        "headline-hero-mobile": ["Inter"],
        "body-base": ["Inter"],
        "label-md": ["Inter"],
        "headline-md": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-sm": ["Inter"],
        "headline-hero": ["Inter"]
      },
      fontSize: {
        badge: ["12px", { lineHeight: "1", fontWeight: "700" }],
        "headline-hero-mobile": ["40px", { lineHeight: "1.1", letterSpacing: "-0.01em", fontWeight: "800" }],
        "body-base": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.5", fontWeight: "500" }],
        "headline-md": ["30px", { lineHeight: "1.25", fontWeight: "700" }],
        "headline-lg": ["40px", { lineHeight: "1.1", fontWeight: "800" }],
        "headline-sm": ["20px", { lineHeight: "1.375", fontWeight: "700" }],
        "headline-hero": ["56px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }]
      }
    }
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries")
  ]
}
